# Normalized Problem


In [1]:
import numpy as np

In [2]:
X = np.random.rand(5, 5)

In [9]:
# Compute the mean of the array X
X_mean = X.mean()
# Compute the standard deviation of the array X
X_std = X.std()
# Normalize X: subtract the mean and divide by the standard deviation

# If you want X_norm as just a numpy array, remove the square brackets.
X_norm = (X - X_mean) / X_std  
# Save the normalized array to a file named 'X_normalized.npy'
np.save('X_normalized.npy', X_norm)
# Print the original array
print("Original Array (X):\n", X)
# Print the normalized array
print("\nNormalized Array (X_normalized):\n", X_norm)

Original Array (X):
 [[0.33038491 0.39797224 0.50359774 0.10127291 0.32711023]
 [0.45490659 0.07862785 0.62337251 0.56545698 0.49258608]
 [0.41049416 0.62599047 0.02121573 0.00273787 0.88126565]
 [0.53807701 0.58924098 0.14885806 0.43398607 0.57209035]
 [0.17116324 0.52335618 0.9936394  0.97701371 0.50585771]]

Normalized Array (X_normalized):
 [[-0.45717297 -0.20059149  0.20039411 -1.32694983 -0.46960464]
 [ 0.01554814 -1.41291717  0.65509454  0.43523009  0.15859062]
 [-0.15305459  0.66503309 -1.63087056 -1.70101795  1.63413312]
 [ 0.33128761  0.52552117 -1.14630255 -0.06387236  0.46041232]
 [-1.06162548  0.27540299  2.0607371   1.99762104  0.20897365]]


# Divisible By 3 Problem

In [10]:
num = np.arange(1, 101)

squares = num ** 2

A = squares.reshape((10,10))

div_by_3 = A[A % 3 == 0]

np.save('div_by_3.npy', div_by_3)

In [12]:
print('Original 10x10 Array:\n')
print(A)

Original 10x10 Array:

[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [17]:
print('Array of Squares Divisible by 3:\n')
print(div_by_3)

Array of Squares Divisible by 3:

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
